PizzaStore/Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    [Authorize(Roles = "Staff")]
    public class CreateModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public CreateModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;
        public async Task<IActionResult> OnPostAsync()
        {
            //Validate account
            var existUserName = await _context.Accounts.FirstOrDefaultAsync(it => it.UserName == Account.UserName);
            if (existUserName != null)
            {
                ModelState.AddModelError(string.Empty, $"UserName {Account.UserName} already exists.");
                return Page();
            }
            Account accountDto = new Account
            {
                UserName = Account.UserName,
                FullName = Account.FullName,
                Password = Account.Password,
                Type = AccountType.Member
            };
            _context.Accounts.Add(Account);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/Accounts/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    public class DeleteModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DeleteModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FirstOrDefaultAsync(m => m.AccountID == id);

            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                Account = account;
                _context.Accounts.Remove(Account);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/Accounts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    public class DetailsModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DetailsModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FirstOrDefaultAsync(m => m.AccountID == id);
            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }
    }
}

PizzaStore/Pages/Accounts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    public class EditModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public EditModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account =  await _context.Accounts.FirstOrDefaultAsync(m => m.AccountID == id);
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }
        [Authorize]
        public async Task<IActionResult> OnPostAsync()
        {
            var adminAccount = await _context.Accounts.FirstOrDefaultAsync(it => it.Type == AccountType.Staff);
            if (adminAccount.AccountID == Account.AccountID)
            {
                Account.Type = AccountType.Staff;
            }
            else
            {
                //Account.Type = AccountType.Member;
                Account.Type = null;
            }
            _context.Attach(Account).State = EntityState.Modified;
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AccountExists(Account.AccountID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToPage("./Index");
        }

        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.AccountID == id);
        }
    }
}

PizzaStore/Pages/CartItem/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.CartItem
{
    public class CreateModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public CreateModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountID", "AccountID");
            return Page();
        }

        [BindProperty]
        public Cart Cart { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Carts.Add(Cart);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/CartItem/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;
using PizzaStore.Utility;

namespace PizzaStore.Pages.CartItem
{
    public class DeleteModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DeleteModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Cart Cart { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FirstOrDefaultAsync(m => m.Id == id);

            if (cart == null)
            {
                return NotFound();
            }
            else
            {
                Cart = cart;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //var allCart = await _context.Carts.CountAsync();
            var cart = await _context.Carts.FindAsync(id);
            if (cart != null)
            {
                Cart = cart;
                _context.Carts.Remove(Cart);
                //HttpContext.Session.SetInt32("CartItemCount", allCart - 1);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/CartItem/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.CartItem
{
    public class DetailsModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DetailsModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public Cart Cart { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }
            else
            {
                Cart = cart;
            }
            return Page();
        }
    }
}

PizzaStore/Pages/CartItem/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.CartItem
{
    public class EditModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public EditModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Cart Cart { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart =  await _context.Carts.FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }
            Cart = cart;
           ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountID", "AccountID");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Cart).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CartExists(Cart.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CartExists(int id)
        {
            return _context.Carts.Any(e => e.Id == id);
        }
    }
}

PizzaStore/Pages/Product/Create.cshtml.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
namespace PizzaStore.Pages.Product
{
    [Authorize(Roles = "Staff")]
    public class CreateModel(PizzaContext context, IMapper mapper, IUploadImageService uploadImageService) : PageModel
    {
        private readonly PizzaContext _context = context;
        private readonly IMapper _mapper = mapper;
        private readonly IUploadImageService _uploadImageService = uploadImageService;
     

        public IActionResult OnGet()
        {
        ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");
        ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "CompanyName");
            return Page();
        }

        [BindProperty]
        public ProductVM ProductVMs { get; set; } = default!;
        [BindProperty]
        public IFormFile File { get; set; } = default!;


        public async Task<IActionResult> OnPostAsync()
        {
            ProductVMs.ProductImage = await _uploadImageService.UploadImage(this.File);
            _context.Products.Add(_mapper.Map<Products>(ProductVMs));
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/Product/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.WebSockets;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Product
{
    public class IndexModel(PizzaContext context, IMapper mapper) : PageModel
    {
        private readonly PizzaContext _context = context;
        private readonly IMapper _mapper = mapper;

        public IList<ProductVM> Products { get;set; } = default!;
        public string? SearchTerm { get; set; }
        public async Task OnGetAsync(string? searchTerm)
        {
            var query = _context.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier)
                .AsQueryable();
            if (!string.IsNullOrEmpty(searchTerm))
            {
                query = query.Where(p => p.ProductName.Contains(searchTerm));
            }

            var results = await query.ToListAsync();
            Products = _mapper.Map<List<ProductVM>>(results);
        }
        public async Task<IActionResult> OnPostDemo()
        {
            return Page();
        }
        // Add to cart
        public async Task<IActionResult> OnPostAddToCartAsync(int productId, int quantity)
        {
           
            var accountName = User.Identity.Name;
            if (accountName == null)
            {
                return RedirectToPage("/Login/Login");
            }
            var account = _context.Accounts.FirstOrDefault(u => u.UserName == accountName);
            var accountID = account.AccountID;


            var product = await _context.Products.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.Account)
                .FirstOrDefaultAsync(c => c.Account.UserName == accountName);

            if (cart == null)
            {
                cart = new Cart
                {
                    AccountID = accountID,
                    CartItemsJson = "[]"
                };
                _context.Carts.Add(cart);
            }

            // Check if the ordered quantity exceeds available stock.
            // Throw an exception if the order quantity is greater than the stock quantity.
            if (product.QuantityPerUnit < quantity)
            {
                throw new Exception("Order quantity cannot exceed available stock.");
            }
            // update CartItemsJson with number of items
            var cartItems = JsonConvert.DeserializeObject<List<CartItems>>(cart.CartItemsJson) ?? new List<CartItems>();
            var existingItem = cartItems.FirstOrDefault(ci => ci.ProductID == productId);

            if (existingItem != null)
            {
                existingItem.Quantity += quantity;
            }
            else
            {
                // add new item into cart
                cartItems.Add(new CartItems
                {
                    ProductID = productId,
                    Quantity = quantity,
                    Price = product.UnitPrice,
                    ProductName = product.ProductName
                });
            }
            // Update Quantity Product in stock
            product.QuantityPerUnit -= quantity;
            cart.CartItemsJson = JsonConvert.SerializeObject(cartItems);

            await _context.SaveChangesAsync();
            HttpContext.Session.SetInt32("CartItemCount", cartItems.Count());
            //var age = HttpContext.Session.GetInt32("CartItemCount").ToString();
            return RedirectToPage("Index");
        }
    }
}

PizzaStore/Pages/Product/Create.cshtml
@page
@model PizzaStore.Pages.Product.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Products</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="ProductVMs.ProductName" class="control-label"></label>
                <input asp-for="ProductVMs.ProductName" class="form-control" />
                <span asp-validation-for="ProductVMs.ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductVMs.Supplier.CompanyName" class="control-label"></label>
                <select asp-for="ProductVMs.SupplierID" class="form-control" asp-items="ViewBag.SupplierID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductVMs.Category.CategoryName" class="control-label"></label>
                <select asp-for="ProductVMs.CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductVMs.QuantityPerUnit" class="control-label"></label>
                <input asp-for="ProductVMs.QuantityPerUnit" class="form-control" />
                <span asp-validation-for="ProductVMs.QuantityPerUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductVMs.UnitPrice" class="control-label"></label>
                <input asp-for="ProductVMs.UnitPrice" class="form-control" />
                <span asp-validation-for="ProductVMs.UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" type="file" class="form-control" />
             </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PizzaStore/Pages/Product/Delete.cshtml
@page
@model PizzaStore.Pages.Product.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.QuantityPerUnit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.QuantityPerUnit)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.UnitPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.UnitPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.ProductImage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.ProductImage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.Category.CategoryID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.Supplier)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.Supplier.SupplierID)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Products.ProductID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

PizzaStore/Pages/Product/Details.cshtml
@page
@model PizzaStore.Pages.Product.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Products</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.QuantityPerUnit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.QuantityPerUnit)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.UnitPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.UnitPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.ProductImage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.ProductImage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.Category.CategoryID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Products.Supplier)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Products.Supplier.SupplierID)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Products.ProductID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

PizzaStore/Pages/Product/Edit.cshtml
@page
@model PizzaStore.Pages.Product.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Products</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Products.ProductID" />
            <div class="form-group">
                <label asp-for="Products.ProductName" class="control-label"></label>
                <input asp-for="Products.ProductName" class="form-control" />
                <span asp-validation-for="Products.ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products.SupplierID" class="control-label"></label>
                <select asp-for="Products.Supplier.CompanyName" class="form-control" asp-items="ViewBag.SupplierID"></select>
                <span asp-validation-for="Products.Supplier.CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products.CategoryID" class="control-label"></label>
                <select asp-for="Products.Category.CategoryName" class="form-control" asp-items="ViewBag.CategoryID"></select>
                <span asp-validation-for="Products.Category.CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products.QuantityPerUnit" class="control-label"></label>
                <input asp-for="Products.QuantityPerUnit" class="form-control" />
                <span asp-validation-for="Products.QuantityPerUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products.UnitPrice" class="control-label"></label>
                <input asp-for="Products.UnitPrice" class="form-control" />
                <span asp-validation-for="Products.UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img src="Product.ProductImage" alt="Product Image" style="max-width: 100px; max-height: 100px;" />
            </div>
            <div class="form-group">
             @*    <label asp-for="Products.ProductImage" class="control-label"></label> *@
                <input asp-for="Products.ProductImage" type="file" class="form-control" accept="image/*" />
                @* <span asp-validation-for="Products.ProductImage" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PizzaStore/Pages/Product/Index.cshtml
@page
@model PizzaStore.Pages.Product.IndexModel

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<form method="get" asp-page="Index" class="mb-3">
    <div class="input-group">
        <input type="text" name="searchTerm" class="form-control" placeholder="Search products..." aria-label="Search products" />
        <button class="btn btn-primary" type="submit">Search</button>
    </div>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].QuantityPerUnit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].ProductImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Supplier)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuantityPerUnit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    <img src="@item.ProductImage" alt="Product Image" style="max-width: 100px; max-height: 100px;" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Supplier.CompanyName)
                </td>
                <td>
                    @if (User.IsInRole("Staff"))
                    {
                        <a asp-page="./Edit" asp-route-id="@item.ProductID">Edit</a>
                        <a asp-page="./Delete" asp-route-id="@item.ProductID">Delete</a>
                    }
                    else
                    {
                        <a asp-page="./Details" asp-route-id="@item.ProductID">Details</a>
                        <br />
                        <form method="post" asp-page-handler="AddToCart" id="form_@item.ProductID" data-ajax="true" data-ajax-method="post" data-ajax-mode="replace" data-ajax-update="#cart-response">
                            <input type="number" name="quantity" id="quantity_@item.ProductID" min="1" value="1" style="width: 50px;" />
                            <input type="hidden" name="productId" value="@item.ProductID" />
                            <input type="hidden" id="availableQuantity_@item.ProductID" value="@item.QuantityPerUnit" />
                            <div class="form-group">
                                <input type="submit" value="Add to Cart" class="btn btn-primary" />
                            </div>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<!-- Popup modal -->
<div id="popup" style="display:none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
                       background-color: white; padding: 20px; border: 1px solid #ccc; box-shadow: 0px 4px 6px rgba(0,0,0,0.1);">
    <p id="popup-message"></p>
    <button onclick="closePopup()">Close</button>
</div>

<script>



    document.addEventListener('DOMContentLoaded', function () {
        const forms = document.querySelectorAll('form[asp-page-handler="AddToCart"]');

        forms.forEach(function (form) {
            form.addEventListener('submit', function (event) {
                const productId = form.id.split('_')[1];
                const enteredQuantity = parseInt(document.getElementById('quantity_' + productId).value, 10);
                const availableQuantity = parseInt(document.getElementById('availableQuantity_' + productId).value, 10);
                if (enteredQuantity > availableQuantity) {
                    showPopup("The entered quantity exceeds the available stock!");
                    event.preventDefault();
                }
            });
        });
    });

    function showPopup(message) {
        const popup = document.getElementById('popup');
        const popupMessage = document.getElementById('popup-message');
        popupMessage.textContent = message;
        popup.style.display = 'block';
    }

    function closePopup() {
        const popup = document.getElementById('popup');
        popup.style.display = 'none';
    }

</script>