PizzaStore/Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    [Authorize(Roles = "Staff")]
    public class CreateModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public CreateModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;
        public async Task<IActionResult> OnPostAsync()
        {
            //Validate account
            var existUserName = await _context.Accounts.FirstOrDefaultAsync(it => it.UserName == Account.UserName);
            if (existUserName != null)
            {
                ModelState.AddModelError(string.Empty, $"UserName {Account.UserName} already exists.");
                return Page();
            }
            Account accountDto = new Account
            {
                UserName = Account.UserName,
                FullName = Account.FullName,
                Password = Account.Password,
                Type = AccountType.Member
            };
            _context.Accounts.Add(Account);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/Accounts/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    public class DeleteModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DeleteModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FirstOrDefaultAsync(m => m.AccountID == id);

            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                Account = account;
                _context.Accounts.Remove(Account);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/Accounts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    public class DetailsModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DetailsModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FirstOrDefaultAsync(m => m.AccountID == id);
            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }
    }
}

PizzaStore/Pages/Accounts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.Accounts
{
    public class EditModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public EditModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account =  await _context.Accounts.FirstOrDefaultAsync(m => m.AccountID == id);
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }
        [Authorize]
        public async Task<IActionResult> OnPostAsync()
        {
            var adminAccount = await _context.Accounts.FirstOrDefaultAsync(it => it.Type == AccountType.Staff);
            if (adminAccount.AccountID == Account.AccountID)
            {
                Account.Type = AccountType.Staff;
            }
            else
            {
                //Account.Type = AccountType.Member;
                Account.Type = null;
            }
            _context.Attach(Account).State = EntityState.Modified;
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AccountExists(Account.AccountID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToPage("./Index");
        }

        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.AccountID == id);
        }
    }
}

PizzaStore/Pages/CartItem/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Pages.CartItem
{
    public class CreateModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public CreateModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountID", "AccountID");
            return Page();
        }

        [BindProperty]
        public Cart Cart { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Carts.Add(Cart);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/CartItem/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;
using PizzaStore.Utility;

namespace PizzaStore.Pages.CartItem
{
    public class DeleteModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;

        public DeleteModel(PizzaStore.Data.PizzaContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Cart Cart { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FirstOrDefaultAsync(m => m.Id == id);

            if (cart == null)
            {
                return NotFound();
            }
            else
            {
                Cart = cart;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //var allCart = await _context.Carts.CountAsync();
            var cart = await _context.Carts.FindAsync(id);
            if (cart != null)
            {
                Cart = cart;
                _context.Carts.Remove(Cart);
                //HttpContext.Session.SetInt32("CartItemCount", allCart - 1);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PizzaStore/Pages/CartItem/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using PizzaStore.Data;
using PizzaStore.Models;
using PizzaStore.Utility.VNPAY;

namespace PizzaStore.Pages.CartItem
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly PizzaStore.Data.PizzaContext _context;
        private readonly IVnPayService _vnPayService;
        public IndexModel(PizzaStore.Data.PizzaContext context, IVnPayService vnPayService)
        {
            _context = context;
            _vnPayService = vnPayService;
        }

        public List<CartItems> CartItems { get; set; } = new List<CartItems>();
        public decimal TotalPrice { get; set; }
        public async Task OnGetAsync()
        {
            var accountName = User.Identity.Name;

            if (accountName != null)
            {
                var account = await _context.Accounts
                    .FirstOrDefaultAsync(u => u.UserName == accountName);

                if (account != null)
                {
                    var cart = await _context.Carts
                        .FirstOrDefaultAsync(c => c.AccountID == account.AccountID);

                    if (cart != null)
                    {
                        CartItems = JsonConvert.DeserializeObject<List<CartItems>>(cart.CartItemsJson) ?? new List<CartItems>();
                        TotalPrice = CartItems.Sum(item => item.Price * item.Quantity);
                        //ViewData["CartItemCount"] = CartItemCount;
                    }
                }
            }
        }

        public async Task<IActionResult> OnPostRemoveFromCartAsync(int productId)
        {
            var accountName = User.Identity.Name;
            var exitProduct = await _context.Products.Where(it => it.ProductID == productId).FirstOrDefaultAsync();
            if (accountName != null)
            {
                var account = await _context.Accounts
                    .FirstOrDefaultAsync(u => u.UserName == accountName);

                if (account != null)
                {
                    var cart = await _context.Carts
                        .FirstOrDefaultAsync(c => c.AccountID == account.AccountID);

                    if (cart != null)
                    {
                        var cartItems = JsonConvert.DeserializeObject<List<CartItems>>(cart.CartItemsJson) ?? new List<CartItems>();

                        var itemToRemove = cartItems.FirstOrDefault(item => item.ProductID == productId);
                        if (itemToRemove != null)
                        {
                            cartItems.Remove(itemToRemove);
                            cart.CartItemsJson = JsonConvert.SerializeObject(cartItems);
                            // return quantity if remove
                            exitProduct.QuantityPerUnit += itemToRemove.Quantity;
                            await _context.SaveChangesAsync();
                            HttpContext.Session.SetInt32("CartItemCount", cartItems.Count());
                        }
                    }
                }
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostCheckoutAsync(DateTime requiredDate, string address, string phone, string contactName , string paymentType = "COD")
        {
            var accountName = User.Identity.Name;
            // vnpay here
            if (accountName != null)
            {
                var account = await _context.Accounts
                    .FirstOrDefaultAsync(u => u.UserName == accountName);
                if (account != null)
                {
                    var cart = await _context.Carts
                        .FirstOrDefaultAsync(c => c.AccountID == account.AccountID);
                    if (cart != null)
                    {
                        var cartItems = JsonConvert.DeserializeObject<List<CartItems>>(cart.CartItemsJson) ?? new List<CartItems>();
                        decimal freight = cartItems.Sum(it => it.Price) * 0.05m;
                        // Create Customer if new customer
                        var customerExist = await _context.Customers.FindAsync(account.AccountID);
                        Customers cus = null;

                        if (customerExist == null)
                        {
                            cus = new Customers
                            {
                                CustomerID = account.AccountID,
                                Address = address,
                                ContactName = contactName,
                                Password = account.Password,
                                Phone = phone,
                            };
                            // update role for account if buyed
                            account.Type = AccountType.Member;
                            _context.Attach(account).State = EntityState.Modified;
                            await _context.Customers.AddAsync(cus);
                            await _context.SaveChangesAsync();
                        }
                        else
                        {
                            cus = customerExist;
                        }

                        Random random = new Random();
                        var cartTotal = cartItems.Sum(it => it.Price * it.Quantity)*1000;
                        // VnPay Here
                        if (paymentType == "VNPAY")
                        {
                            var vnPayModel = new VnPaymentRequestModel
                            {
                                Amount = (Double)cartTotal,
                                CreatedDate = DateTime.UtcNow,
                                Description = $"{account.FullName} - {phone}",
                                FullName = contactName,
                                OrderId = random.Next(1000, 100000),
                            };
                            return Redirect(_vnPayService.CreatePaymentUrl(HttpContext, vnPayModel));
                        }

                        // Add ORDER
                        Orders orders = new Orders
                        {
                            CustomerID = cus.CustomerID,
                            OrderDate = DateTime.Now,
                            RequiredDate = requiredDate,
                            Freight = freight,
                            ShippedDate = requiredDate,
                            ShipAddress = address,
                        };
                        await _context.Orders.AddAsync(orders);
                        await _context.SaveChangesAsync();
                        // add into OrderDetail
                        var orderDetailsList = new List<OrderDetails>();
                        foreach (var item in cartItems)
                        {
                            OrderDetails orderDetails = new OrderDetails
                            {

                                OrderID = orders.OrderID,
                                ProductID = item.ProductID,
                                Quantity = item.Quantity,
                                UnitPrice = item.Price,
                            };
                            orderDetailsList.Add(orderDetails);
                        }
                        // Add range of OrderDetails
                        await _context.OrderDetails.AddRangeAsync(orderDetailsList);
                        cart.CartItemsJson = "[]";
                        await _context.SaveChangesAsync();
                    }
                }
            }

            return RedirectToPage("/Product/Index");
        }
        [Authorize]
        public IActionResult PaymentFail()
        {
            return Page();
        }
    }
}

PizzaStore/Pages/CartItem/Create.cshtml
@page
@model PizzaStore.Pages.CartItem.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cart.AccountID" class="control-label"></label>
                <select asp-for="Cart.AccountID" class ="form-control" asp-items="ViewBag.AccountId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cart.CartItemsJson" class="control-label"></label>
                <input asp-for="Cart.CartItemsJson" class="form-control" />
                <span asp-validation-for="Cart.CartItemsJson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PizzaStore/Pages/CartItem/Delete.cshtml
@page
@model PizzaStore.Pages.CartItem.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cart.Account)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cart.Account.AccountID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cart.CartItemsJson)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cart.CartItemsJson)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Cart.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

PizzaStore/Pages/CartItem/Details.cshtml
@page
@model PizzaStore.Pages.CartItem.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cart.Account)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cart.Account.AccountID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cart.CartItemsJson)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cart.CartItemsJson)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Cart.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

PizzaStore/Pages/CartItem/Edit.cshtml
@page
@model PizzaStore.Pages.CartItem.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Cart.Id" />
            <div class="form-group">
                <label asp-for="Cart.AccountID" class="control-label"></label>
                <select asp-for="Cart.AccountID" class="form-control" asp-items="ViewBag.AccountId"></select>
                <span asp-validation-for="Cart.AccountID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cart.CartItemsJson" class="control-label"></label>
                <input asp-for="Cart.CartItemsJson" class="form-control" />
                <span asp-validation-for="Cart.CartItemsJson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PizzaStore/Pages/CartItem/Index.cshtml
@page
@model PizzaStore.Pages.CartItem.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Shopping Cart</h2>

@if (Model.CartItems.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CartItems)
            {
                <tr>
                    <td>@item.ProductName</td>
                    <td>@item.Quantity</td>
                    <td>@item.Price</td>
                    <td>@(item.Price * item.Quantity)</td>
                    <td>
                        <form method="post" asp-page-handler="RemoveFromCart" asp-route-productId="@item.ProductID">
                            <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <h3>Total Amount: @Model.TotalPrice.ToString("C")</h3>

    <form method="post" asp-page-handler="Checkout" class="mt-3">
        <button type="button" class="btn btn-primary" onclick="openModal()">Checkout</button>
    </form>

    <form method="post" asp-page-handler="Checkout" class="mt-3">
        <input type="hidden" name="paymentType" value="VNPAY" />
        <button type="submit" class="btn btn-primary">Checkout With VNPAY</button>
    </form>
}
else
{
    <p>Empty.</p>
}

<!-- Popup Modal -->
<div id="checkoutModal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">&times;</span>
        <h2>Enter Shipping Information</h2>
        <form id="checkoutForm" method="post" asp-page-handler="Checkout" onsubmit="return validateForm()">
            <div class="form-group">
                <label for="contactName">Contact Name:</label>
                <input type="text" id="contactName" name="contactName" required class="form-control" />
            </div>
            <div class="form-group">
                <label for="phone">Phone Number:</label>
                <input type="tel" id="phone" name="phone" required class="form-control" pattern="^\+?[0-9\s]*$" title="Please enter a valid phone number (numbers only)."/>
            </div>
            <div class="form-group">
                <label for="address">Address:</label>
                <input type="text" id="address" name="address" required class="form-control" />
            </div>
            <div class="form-group">
                <label for="requiredDate">Delivery Date:</label>
                <input type="date" id="requiredDate" name="requiredDate" required class="form-control" min="@DateTime.Now.ToString("yyyy-MM-dd")" />
            </div>
            <button type="submit" class="btn btn-primary">Confirm</button>
        </form>
    </div>
</div>

<script>
    function validateForm() {
        const phone = document.getElementById("phone").value;
        const phonePattern = /^\+?[0-9\s]*$/; 

        if (!phonePattern.test(phone)) {
            alert("Please enter a valid phone number.");
            return false;
        }

        return true;
    }

    function openModal() {
        const today = new Date();
        const day = String(today.getDate()).padStart(2, '0');
        const month = String(today.getMonth() + 1).padStart(2, '0');
        const year = today.getFullYear();
        const minDate = `${year}-${month}-${day}`;

        document.getElementById("requiredDate").setAttribute("min", minDate);
        document.getElementById("checkoutModal").style.display = "flex";
    }

    function closeModal() {
        document.getElementById("checkoutModal").style.display = "none";
    }
    
    document.querySelector("button.btn.btn-primary").addEventListener("click", function (event) {
        event.preventDefault();
        openModal();
    });
</script>